### ISSUE TITLE
linux build?

### ISSUE THREAD

**Issue by jabuxas** [ShadowMonster99/millennium-steam-patcher#13]
how hard would it be to port this to linux?

**Comment by ShadowMonster99** [comment]
You would need to rewrite a lot of the patcher. It uses the windows api for a lot of calls. If you know what you are doing its possible you could build the app as an executable instead of a dynamic linked library, then you could possibly use Wine or some other alternative compatibility layer. Additionally the patcher wouldn't be as integrated into the steam client as you would have to find a way to run daemon apps on linux potentially at startup, or whenever Steam starts.

But if your looking to know if Millennium *will* be ported to linux, no there are no current plans unfortunately.

**Comment by Enderteck** [comment]
:'(

**Comment by ShadowMonster99** [comment]
You can build from source, its currently in development.

**Comment by Enderteck** [comment]
Ok, any doc yet to do that ?
