### ISSUE TITLE
"n.reduce is not a function" (Bug)

### ISSUE THREAD

**Issue by Nthingxhere** [ShadowMonster99/millennium-steam-patcher#16]
## what is the problem
I have installed Steam and wanted to install millenium too but the installer gives me the following error:
`n.reduce is not a function` with some line numbers like in the pic below:

<img width="890" alt="image" src="https://github.com/ShadowMonster99/millennium-steam-patcher/assets/76117403/014daed9-8fa4-4a8d-b5ab-4903cf8ee743">

## how I got there

1. I downloaded the installer
2. I opened it and clicked "Install Millenium"

I hope this is submitted correctly

**Comment by ShadowMonster99** [comment]
Millennium is slowly migrating to a organization, so a more up to date version of the installer can be found here
- https://github.com/SteamClientHomebrew/Installer/releases/tag/1.0.0

Hopefully it fixes the [issue](https://github.com/SteamClientHomebrew/Installer/commit/6f74b8cd1438c8402ce6e125b634b8a7181bf3c3). From a surface level analysis it seems to be a fault because it cant connect to GitHub, specifically this [link](https://api.github.com/repos/ShadowMonster99/millennium-steam-binaries/releases/latest). Ensure that this properly loads.
